apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: awz6z5u6w-nodejs 
  janus-idp.io/tekton: awz6z5u6w-nodejs
  backstage.io/kubernetes-id: awz6z5u6w-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: awz6z5u6w-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  